"""
report.py
---------
Generates a human-readable Markdown report and matplotlib charts summarizing
utilization metrics and simulation results, suitable for sharing with OR
leadership or including in a portfolio write-up.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from .metrics import UtilizationMetrics
from .simulate import SimulationResult


def _save_utilization_chart(daily_room_summary: pd.DataFrame, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(9, 5))
    room_avg = (
        daily_room_summary.groupby("room_id")["utilization_pct"].mean().sort_values()
    )
    ax.barh(room_avg.index.astype(str), room_avg.values, color="#2E86AB")
    ax.axvline(75, color="gray", linestyle="--", linewidth=1, label="75% benchmark")
    ax.set_xlabel("Average Utilization (%)")
    ax.set_title("Average Room Utilization by Room")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def _save_delay_overrun_chart(case_level: pd.DataFrame, out_path: Path) -> None:
    completed = case_level[case_level["is_completed"]]
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(
        completed["start_delay_min"].dropna(),
        bins=30,
        alpha=0.6,
        label="Start delay (min)",
        color="#F18F01",
    )
    ax.hist(
        completed["overrun_min_clipped"].dropna(),
        bins=30,
        alpha=0.6,
        label="Overrun (min)",
        color="#C73E1D",
    )
    ax.set_xlabel("Minutes")
    ax.set_ylabel("Number of cases")
    ax.set_title("Distribution of Start Delays and Overruns")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def _save_turnaround_chart(turnaround_times: pd.DataFrame, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(9, 5))
    if not turnaround_times.empty:
        ax.hist(turnaround_times["turnaround_min"].dropna(), bins=30, color="#3B8686")
    ax.set_xlabel("Turnaround time (min)")
    ax.set_ylabel("Number of case transitions")
    ax.set_title("Room Turnaround Time Distribution")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def generate_markdown_report(
    metrics: UtilizationMetrics,
    output_dir: str,
    simulation: Optional[SimulationResult] = None,
    title: str = "OR / Procedure Room Utilization Report",
) -> str:
    """
    Generates a Markdown report + PNG charts in output_dir.
    Returns the path to the generated markdown file.
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    charts_dir = out_dir / "charts"
    charts_dir.mkdir(exist_ok=True)

    util_chart = charts_dir / "utilization_by_room.png"
    delay_chart = charts_dir / "delay_overrun_distribution.png"
    turnaround_chart = charts_dir / "turnaround_distribution.png"

    _save_utilization_chart(metrics.daily_room_summary, util_chart)
    _save_delay_overrun_chart(metrics.case_level, delay_chart)
    _save_turnaround_chart(metrics.turnaround_times, turnaround_chart)

    o = metrics.overall

    lines = []
    lines.append(f"# {title}\n")
    lines.append(
        f"_Generated by `or_utilization` on {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}_\n"
    )

    lines.append("## Executive Summary\n")
    lines.append(f"- **Room-days analyzed:** {o['n_room_days']}")
    lines.append(
        f"- **Cases scheduled:** {o['n_cases_scheduled']} "
        f"({o['n_cases_completed']} completed, {o['n_cases_cancelled']} cancelled)"
    )
    lines.append(f"- **Cancellation rate:** {o['cancellation_rate_pct']:.1f}%")
    lines.append(f"- **Overall room utilization:** {o['overall_utilization_pct']:.1f}%")
    lines.append(f"- **Average start delay:** {o['avg_start_delay_min']:.1f} min")
    lines.append(f"- **Average overrun (when over):** {o['avg_overrun_min']:.1f} min")
    lines.append(
        f"- **% of cases that overran scheduled time:** {o['pct_cases_overrun']:.1f}%"
    )
    lines.append(
        f"- **Average turnaround time between cases:** {o['avg_turnaround_min']:.1f} min\n"
    )

    lines.append("## Utilization by Room\n")
    lines.append(f"![Utilization by room](charts/{util_chart.name})\n")

    lines.append("## Delay and Overrun Distribution\n")
    lines.append(f"![Delay and overrun distribution](charts/{delay_chart.name})\n")

    lines.append("## Turnaround Time Distribution\n")
    lines.append(f"![Turnaround distribution](charts/{turnaround_chart.name})\n")

    lines.append("## Surgeon-Level Summary\n")
    surgeon_table = metrics.surgeon_summary.round(1).to_markdown(index=False)
    lines.append(surgeon_table + "\n")

    lines.append("## Room / Day Summary (first 15 rows)\n")
    room_day_table = (
        metrics.daily_room_summary.head(15).round(1).to_markdown(index=False)
    )
    lines.append(room_day_table + "\n")

    if simulation is not None:
        s = simulation.summary
        a = simulation.assumptions
        lines.append(f"## Simulation: '{simulation.scenario_name}'\n")
        lines.append("**Assumptions:**\n")
        for k, v in a.items():
            lines.append(f"- `{k}` = {v}")
        lines.append("")
        lines.append("**Results:**\n")
        lines.append(
            f"- Baseline avg utilization: {s['baseline_utilization_pct']:.1f}%"
        )
        lines.append(
            f"- Projected avg utilization: {s['projected_utilization_pct']:.1f}%"
        )
        lines.append(
            f"- Total minutes reclaimed via efficiency improvements: {s['total_reclaimed_minutes']:.0f} min"
        )
        lines.append(
            f"- Additional cases estimated from efficiency gains alone: "
            f"**{s['est_additional_cases_from_efficiency_only']:.1f}**"
        )
        lines.append(
            f"- Additional cases estimated including existing unused idle time: "
            f"**{s['est_additional_cases_incl_existing_idle']:.1f}**\n"
        )
        lines.append(
            "> This is a transparent, assumption-driven estimate — not a discrete-event "
            "simulation. Every number traces back to a stated input assumption above so "
            "it can be sanity-checked and adjusted by OR leadership.\n"
        )

    report_path = out_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return str(report_path)
